name: SonarCloud
#on:
#  push:
 #   branches:
  #    - master
 # pull_request:
  #  types: [opened, synchronize, reopened]

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: string
                
permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish-image:
    uses: tsvsumanth47/github-reusable-workflow/.github/workflows/maven-ci.yaml@maven-ci
    with:
      config-path: dummy
    secrets:
      SONAR_TOKEN: ${{ secrets.token }}